### ISSUE TITLE
getTransaction requires txindex

### ISSUE THREAD

**Issue by oleksandr-shubin** [Polve/bitcoin-rpc-client#105] opened 2019-11-24 18:35 UTC
I am using bitcoin-rpc-client in conjunction with walletnotify to get transaction data upon first confirmation. The problem is that [`getTransaction`](https://github.com/Polve/bitcoin-rpc-client/blob/master/src/main/java/wf/bitcoin/javabitcoindrpcclient/BitcoinJSONRPCClient.java#L989) method returns `Invalid Tx` because of the following error under the hood: 

> No such mempool transaction. Use -txindex to enable blockchain transaction queries. Use gettransaction for wallet transactions.

I can set `txindex`, but it's redundant for me, as I am interested only in my wallet transactions, moreover AFAIU it will add some performance overhead.
I've found the [source](https://github.com/Polve/bitcoin-rpc-client/issues/88) of the problem, but still can't understand the solution. Both `getTransaction` and `getRawTransaction` methods now do `getrawtransaction` under the hood which is inconvenient when one works with his own wallet transactions only

**Comment by cd2357** [comment] 2020-01-24 07:17
Have you tried using listUnspent? That also goes over transactions in the mempool. Only difference is it works with utxos instead of transactions.

**Comment by cd2357** [comment] 2020-01-24 07:46
See discussion [here](https://bitcoin.stackexchange.com/questions/35707/what-are-pros-and-cons-of-txindex-option) about why `txindex` is needed for `getTransaction`.

If you're working and only interested in your own wallet's transactions, have a look at [listUnspent](https://github.com/Polve/bitcoin-rpc-client/blob/master/src/main/java/wf/bitcoin/javabitcoindrpcclient/BitcoinJSONRPCClient.java#L654) which lists the utxos of the addresses in your wallet. This does not need `txindex`. You could call it for example using blocknotify, which indicates to you that 1) there are potentially new wallet transactions, and 2) relevant mempool transactions may have gotten 1 confirmation.

**Comment by cd2357** [comment] 2020-01-24 07:47
@Polve -- I suggest you can close this issue, since it works as designed (`getTransaction` is supposed to need `txindex`).

**Comment by Polve** [comment] 2020-01-24 07:49
Thanks @cd2357

**Closed by Polve** 2020-01-24 07:49 UTC
